### ISSUE TITLE
How often are files written to USB?

### ISSUE THREAD

**Issue by sorano** [knudsvik/ctc_csv#1]
Hej!

Found this repo yesterday evening and decided to give it a try.
Formatted an USB stick with FAT32. Inserted into my EcoZenith250L and enabled logging in options.

Today I pulled the stick out to check if any files had been written but it was just as empty as when I formatted.
I'm thinking possibly an incompatible USB-stick or buggy firmware:

```
Displaykort: 20170119
VP-styrkort: 20160909
```

If you could let me know how often the logging is writing file to disk it would help me troubleshoot what's wrong.

Thanks in advance 👍🏻

**Comment by sorano** [comment]
Ok, just took a look at your example csv file and it looks like it should be written once or twice every minute.

**Comment by sorano** [comment]
Alright, so SanDisk USB Cruzer Blade 8GB does not seem to compatible which is a shame because the form factor fits perfect.
Tried reformatting and cleaning with diskpart but nothing gets written to it.

I ended up using a USB 3.0 memory stick I had lying that was small enough to fit behind the display.

**Comment by knudsvik** [comment]
Did you get it to work? I am not sure why some memory sticks work and some not. I got mine sent from CTC to do some testing.

**Comment by sorano** [comment]
@knudsvik 
Yeah, when using the USB 3.0 memory I had lying I saw 2 files being written to it:
{yearmonthday}.CSV and SETTINGS.BIN

Out of curiosity. Have you tried to decode the SETTINGS.BIN to see what it contains?

Also, have you looked into any way to read the data over network?

I'm thinking something like an Android device using https://www.drivedroid.io/#about with USB OTG so it can charge and emulate at the same time.

Or maybe a raspberry pi emulating a USB drive.

**Comment by sorano** [comment]
Another question, hope you dont mind 😃

Can I find the grafana dashboard anywhere?

**Comment by knudsvik** [comment]
I haven't looked at the bin file no. I have been thinking about getting the data over the network, but not more than some googling. As far as I have read the raspberry PI zero could be used for that purpose, would be really interesting to check out. 

You need to set up Grafana separately from influxdb as it just visualisation, but it connects quite easily to the influxdb (or other databases like sql). I use docker containers for both.

**Comment by sorano** [comment]
> You need to set up Grafana separately from influxdb as it just visualisation, but it connects quite easily to the influxdb (or other databases like sql). I use docker containers for both.

Yeah, I'm just talking about the grafana dashboard not the service itself.
Like, if you've shared it at: https://grafana.com/grafana/dashboards

**Comment by knudsvik** [comment]
> Yeah, I'm just talking about the grafana dashboard not the service itself.
> Like, if you've shared it at: https://grafana.com/grafana/dashboards

Ahh, I see. I tried to share it, but something is wrong. I uploaded it to my GitHub repo though, you should see it in the resources folder.

**Comment by sorano** [comment]
Just a minor observation on my end. It seems the logged data is very firmware specific.

This is a logged entry generated from Displaykort: 20170119;
`20210117 13:07,1,-1.0,57,55,20.1,-999.9,27,22,0,0.0,2.0,1.1,1.2,0,0,0,0,0,0.3,0.0,25,0.0,53.6,53.5,38.1,24.4,16.4,29.8,3.5,5.1,5.1,0.0,-`

33 CSV's, the same amount as you parse in your python script

This is a logged entry from Displaykort: 20191122 on same hardware;
`20210121 09:36,2,2.0,59,53,20.9,-999.9,32,31,1,0,0,0,0.0,10.7,1.1,1.2,4,0,0,0,0,158,2.6,0.0,0,0.0,9.6,10.6,24.7,20.7,10.5,14.3,3.5,5.5,5.5,0.0,0,`

38 commas, 37 values, for some reason line ends with a comma before linebreak

**Comment by sorano** [comment]
Another update if you are interested @knudsvik 
I spoke with a certified CTC technician today since my EcoZenith i250 was showing an error code after the firmware update that had never showed up before.

He told me that CTC have adjusted the margins for errors to protect the heat pump in newer firmware. So basically my heat pump could have been underperforming for as long as I was on the older firmware. And I would never have known unless I upgraded.

**Comment by knudsvik** [comment]
> Just a minor observation on my end. It seems the logged data is very firmware specific.
> 
> This is a logged entry generated from Displaykort: 20170119;
> `20210117 13:07,1,-1.0,57,55,20.1,-999.9,27,22,0,0.0,2.0,1.1,1.2,0,0,0,0,0,0.3,0.0,25,0.0,53.6,53.5,38.1,24.4,16.4,29.8,3.5,5.1,5.1,0.0,-`
> 
> 33 CSV's, the same amount as you parse in your python script
> 
> This is a logged entry from Displaykort: 20191122 on same hardware;
> `20210121 09:36,2,2.0,59,53,20.9,-999.9,32,31,1,0,0,0,0.0,10.7,1.1,1.2,4,0,0,0,0,158,2.6,0.0,0,0.0,9.6,10.6,24.7,20.7,10.5,14.3,3.5,5.5,5.5,0.0,0,`
> 
> 38 commas, 37 values, for some reason line ends with a comma before linebreak

Hm that's interesting. So that make's it even harder to identify which column is which data. Where did you find the firmware version?

**Comment by sorano** [comment]
> Hm that's interesting. So that make's it even harder to identify which column is which data. 

Yeah...
I've asked if there is any documentation regarding the csv's and am waiting for an answer.

> Where did you find the firmware version?

I contacted their customer service on info [a] enertech.se and asked if there was any newer firmware for ecozenith i250.
I also asked for a changelog but that doesn't seem to exist unfortunately.

**Comment by knudsvik** [comment]
I tried in several ways to use a raspberry pi zero as a target drive, formatted properly as fat16 (like my ctc thumb drive), but never with luck. Finally I now bought a new display from CTC which came with Modbus capability rendering this method unecessary for me as I know have real-time access to all data. I tested logging to usb with the new display as well, works as intended, but now all data are labeled in the csv file.

**Comment by sorano** [comment]
Which display did you buy?
I've been running a pi zero with the g_mass_storage module. And it's been working pretty ok.

Could you give an example on how the new csv values look?

**Comment by knudsvik** [comment]
There’s not any good product name for it. One says just Display and the other says Connect+. It has a standard RJ45 plug on the back of the display to connect to network (and optio ally connect+). I use it for Modbus TCP which seems to work flawless. 

Sample csv file available in repo.
